name: Build Test Application

on:
  workflow_call: {}
  workflow_dispatch: {}
  push:
jobs:
  build:
    name: Build Test App
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build Test Application with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2.1
          target: esp32
      - name: Test Embeded
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 180000
          fail_text: FAILED
          scenario: "senario.test.yaml"